apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: hello-world-strip-prefix
  namespace: production
spec:
  stripPrefix:
    prefixes:
      - /hello
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hello-world-route
  namespace: production
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/hello`)
      kind: Rule
      middlewares:
        - name: hello-world-strip-prefix
      services:
        - name: hello-world
          port: 80

